### ISSUE TITLE
Test tests/test_libzim_creator.py::test_creator_additem fails

### ISSUE THREAD

**Issue by OTLabs** [openzim/python-libzim#180]
I am building package for Alpine Linux, musl, v3.3.0 and got following [failing test](https://gitlab.alpinelinux.org/otlabs/aports/-/jobs/1183133#L282):

```
=========================== short test summary info ============================
FAILED tests/test_libzim_creator.py::test_creator_additem - AssertionError: Regex pattern did not match.
 Regex: 'takes exactly 1 positional argument'
 Input: '_Creator.add_item() takes no keyword arguments'
======================== 1 failed, 105 passed in 3.16s =========================
```
Package for v3.2.0 was successfully built.

**Comment by rgaudin** [comment]
This is due to your Cython version (`0.29`). We've [updated our Cython dependency to `3.0.5`](https://github.com/openzim/python-libzim/blob/main/setup.cfg#L45) which introduced a change in exception handling which is why this test was changed.
Please update Cython or use our wheels.

Note: thanks to this ticket I realize we've left the ignore rule about musl and did not build/upload the musl wheels to PyPi. Fixing that now.

**Comment by rgaudin** [comment]
Wheels are now available on [PyPI](https://pypi.org/project/libzim/#files)
